---
title: "PEGS_Phenotyping"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Lower GI Polyps
---------------------
```{r}

load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')

```



```{r}

table(clean_he$he_f041_polyps)

cancer_cols <- names(clean_he)[grep('cancer',names(clean_he),ignore.case = T)]

cancer_ex <- c('age|sis|bro|dad|mom')

cancer_cols <- cancer_cols[-grep(cancer_ex,cancer_cols,ignore.case = T)]

gi_cols <- c('he_f038_lactose_intolerance','he_f039_crohns','he_f040_ulcerative_colitis')

exclusion_cols <- c(cancer_cols,gi_cols)

```

```{r}



ex_df <- clean_he[c(exclusion_cols)] 
ex_df[] <- lapply(ex_df, function(x) as.numeric(as.character(x))) 


d <- ex_df %>% 
  as.data.frame(.) %>% 
  mutate(sum = rowSums(.,na.rm = T)) %>% dplyr::select(sum,everything())

epr_number <- clean_he$epr_number

ex_df <- cbind(epr_number,d) %>% dplyr::select(epr_number,sum)

```

```{r}

he_vars <- clean_he %>% dplyr::select(epr_number,he_f041_polyps,he_age_derived)




pheno_data <- left_join(he_vars,ex_df, by = 'epr_number') %>% 
  mutate(Flag = ifelse(sum == 0,0,1)) %>% 
  mutate(Lower_GI_Polyps = case_when(he_f041_polyps == 1 ~ 1,
                                     he_f041_polyps == 0 & Flag == 0 ~ 0,
                                     TRUE ~ NA_real_)) %>% 
  dplyr::select(epr_number,Lower_GI_Polyps)


lower_gi <- pheno_data

```


```{r}
save(lower_gi,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/lower_gi.RData')
```


```{r}
final_he_data <- left_join(clean_he,pheno_data, by = 'epr_number')
```



```{r}
rm(list = ls())

```


Fibroids 
--------------------
```{r}

load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')

```


```{r}



f_he <- clean_he %>% dplyr::filter(`_he_gender_`==1)

table(f_he$he_m091_uterine_tumors)

f_he[] <- lapply(f_he, function(x) as.numeric(as.character(x))) 


cancer_cols <- names(clean_he)[grep('cancer',names(clean_he),ignore.case = T)]

cancer_ex <- c('age|sis|bro|dad|mom')

cancer_cols <- cancer_cols[-grep(cancer_ex,cancer_cols,ignore.case = T)]



exclusion_cols <- c('he_m092_ovarian_cysts','he_m089_endometriosis','he_m090_uterine_polyps')


```


```{r}

# 
 f_ex <- f_he[c(exclusion_cols)] %>% 
   mutate(sum = rowSums(.,na.rm = T)) %>% dplyr::select(sum,everything())


epr_number <- f_he$epr_number

ex_df <- cbind(epr_number,f_ex) %>% dplyr::select(epr_number,sum)

he_vars <- f_he %>% dplyr::select(epr_number,he_m091_uterine_tumors,he_age_derived)


pheno_data <- left_join(he_vars,ex_df, by = 'epr_number') %>% 
  mutate(Flag = ifelse(sum == 0,0,1)) %>% 
   mutate(Fibroids = case_when(he_m091_uterine_tumors == 1 ~ 1,
                                     he_m091_uterine_tumors == 0 & Flag == 0 ~ 0,
                                     TRUE ~ NA_real_)) %>% 
  dplyr::select(epr_number,Fibroids)

table(pheno_data$Fibroids)

Fibroids <- pheno_data
```

```{r}
save(Fibroids,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Fibroids.RData')
```

```{r}
final_he_data <- left_join(clean_he,pheno_data, by = 'epr_number')
```



```{r}
rm(list = ls())

```

Bone Loss
----------

```{r}
load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')


```

```{r}
table(clean_he$he_j062_bone_loss)
table(clean_he$he_j063_osteoporosis)
table(clean_he$he_o106_cancer_bone_PARQ_CHILDQ)
```

```{r}

clean_he[] <- lapply(clean_he, function(x) as.numeric(as.character(x))) 

bone_cancer <- clean_he %>% dplyr::select(epr_number,he_o106_cancer_bone_PARQ_CHILDQ)
bone_cancer[is.na(bone_cancer)] <- 0

ex_df <- clean_he %>% 
  dplyr::filter(!is.na(he_j062_bone_loss) & !is.na(he_j063_osteoporosis) ) %>% 
  dplyr::select(epr_number,he_j062_bone_loss,he_j063_osteoporosis) %>% 
  column_to_rownames('epr_number') %>% 
  dplyr::mutate(sum = rowSums(.,na.rm = T),
                Bone_Loss = ifelse(sum >0,1,0)) %>% 
  rownames_to_column('epr_number') %>% 
  mutate(epr_number = as.numeric(as.character(epr_number))) %>% 
  left_join(.,bone_cancer, by = "epr_number") %>% 
  mutate(Bone_Loss = ifelse(he_o106_cancer_bone_PARQ_CHILDQ == 1 & Bone_Loss == 0,NA,Bone_Loss) ) %>% 
  dplyr::select(epr_number,Bone_Loss)


```


```{r}

Bone_Loss <- ex_df 
save(Bone_Loss,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Bone_Loss.RData')
```

```{r}
rm(list = ls())
```


Migraines
-------------------
```{r}
load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')
```

```{r}
table(clean_he$he_e032_migraine)
table(clean_he$he_o107_cancer_brain_PARQ_CHILDQ)
```

```{r}

clean_he[] <- lapply(clean_he, function(x) as.numeric(as.character(x))) 


cancer <- clean_he %>% dplyr::select(epr_number,he_o107_cancer_brain_PARQ_CHILDQ)
cancer[is.na(cancer)] <- 0


ex_df <- clean_he %>% 
  dplyr::select(epr_number,he_e032_migraine) %>% 
  dplyr::mutate(Migraines = ifelse(he_e032_migraine == 1,1,0)) %>% 
  mutate(epr_number = as.numeric(as.character(epr_number))) %>% 
  left_join(.,cancer, by = "epr_number") %>% 
  mutate(Migraines = ifelse(he_o107_cancer_brain_PARQ_CHILDQ == 1 & Migraines == 0,NA,Migraines) ) %>% 

  dplyr::select(epr_number,Migraines)


Migraines <- ex_df

```


```{r}
save(Migraines,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Migraines.RData')
```

```{r}
rm(list = ls())
```

Anemia
----------------

```{r}
load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')
```


```{r}

table(clean_he$he_i059_iron_anemia)
xtabs(~ he_i059_iron_anemia + he_i060_pernicious_anemia + he_i061_sickle_cell + he_o115_cancer_leukemia_PARQ_CHILDQ,data = clean_he)

```

```{r}

exclusion_cols <- c('he_i060_pernicious_anemia','he_i061_sickle_cell','he_o115_cancer_leukemia_PARQ_CHILDQ')


clean_he[] <- lapply(clean_he, function(x) as.numeric(as.character(x))) 

d <- clean_he[c(exclusion_cols)] %>% 
  mutate(sum = rowSums(.,na.rm = T)) %>% dplyr::select(sum,everything())

epr_number <- clean_he$epr_number

ex_df <- cbind(epr_number,d) %>% dplyr::select(epr_number,sum)

he_vars <- clean_he %>% dplyr::select(epr_number,he_i059_iron_anemia)

pheno_data <- left_join(he_vars,ex_df, by = 'epr_number') %>% 
  mutate(Flag = ifelse(sum == 0,0,1)) %>% 
   mutate(Iron_Def_Anemia = case_when(he_i059_iron_anemia == 1 ~ 1,
                                     he_i059_iron_anemia == 0 & Flag == 0 ~ 0,
                                     TRUE ~ NA_real_)) %>%  
  dplyr::select(epr_number,Iron_Def_Anemia)


Iron_Def_Anemia <- pheno_data
```


```{r}
save(Iron_Def_Anemia,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Iron_Def_Anemia.RData')
```


```{r}
rm(list = ls())
```



Ovarian Cysts
----------------
```{r}

load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')

```


```{r}



f_he <- clean_he %>% dplyr::filter(`_he_gender_`==1)

table(f_he$he_m092_ovarian_cysts)

f_he[] <- lapply(f_he, function(x) as.numeric(as.character(x))) 


cancer_cols <- names(clean_he)[grep('cancer',names(clean_he),ignore.case = T)]

cancer_ex <- c('age|sis|bro|dad|mom')

cancer_cols <- cancer_cols[-grep(cancer_ex,cancer_cols,ignore.case = T)]




exclusion_cols <- c('he_m091_uterine_tumors','he_m089_endometriosis','he_m090_uterine_polyps')


```

```{r}


f_ex <- f_he[c(exclusion_cols)] %>% 
  mutate(sum = rowSums(.,na.rm = T)) %>% dplyr::select(sum,everything())

epr_number <- f_he$epr_number

ex_df <- cbind(epr_number,f_ex) %>% dplyr::select(epr_number,sum)

he_vars <- f_he %>% dplyr::select(epr_number,he_m092_ovarian_cysts)


pheno_data <- left_join(he_vars,ex_df, by = 'epr_number') %>% 
  mutate(Flag = ifelse(sum == 0,0,1)) %>% 
  mutate(Ovarian_Cysts = case_when(he_m092_ovarian_cysts == 1 ~ 1,
                                     he_m092_ovarian_cysts == 0 & Flag == 0 ~ 0,
                                     TRUE ~ NA_real_)) %>%  
  dplyr::select(epr_number,Ovarian_Cysts)

```

```{r}

Ovarian_Cysts <- pheno_data

save(Ovarian_Cysts,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Ovarian_Cysts.RData')
```


```{r}
rm(list = ls())
```


Asthma
----------------
```{r}

load('/Volumes/PEGS/StatGen/lloyddt/Phenotyping/clean_he.Rdata')

```


```{r}
exclusion_cols <- c('he_d025_copd','he_d026_ipf','he_d027_tb_PARQ',"he_d028_cough_breathlessness","he_d029_chest_wheeze")
ex_df <- clean_he[c(exclusion_cols)] 
ex_df[] <- lapply(ex_df, function(x) as.numeric(as.character(x))) 


d <- ex_df %>% 
  as.data.frame(.) %>% 
  mutate(sum = rowSums(.,na.rm = T)) %>% dplyr::select(sum,everything())


epr_number <- clean_he$epr_number

ex_df <- cbind(epr_number,d) %>% dplyr::select(epr_number,sum)


```


```{r}

he_vars <- clean_he %>% dplyr::select(epr_number,he_d030_asthma_PARQ)




pheno_data <- left_join(he_vars,ex_df, by = 'epr_number') %>% 
  mutate(Flag = ifelse(sum == 0,0,1)) %>% 
  mutate(Asthma = case_when(he_d030_asthma_PARQ == 1 ~ 1,
                                     he_d030_asthma_PARQ == 0 & Flag == 0 ~ 0,
                                     TRUE ~ NA_real_)) %>% 
  dplyr::select(epr_number,Asthma)

table(pheno_data$Asthma)

Asthma <- pheno_data

```

```{r}
save(Asthma,file = '/Volumes/PEGS/StatGen/lloyddt/Phenotyping/Phenotype_Files/Asthma.RData')

```






